# https://github.com/kentcdodds/kentcdodds.com/blob/main/.github/workflows/deployment.yml
name: Code Check
on:
  push:
    branches:
      - master
  pull_request: {}

concurrency:
  group: ${{ github.job }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: ⬣ ESLint
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v6

      - name: ⎔ Setup node
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          cache: npm

      - name: 📥 Install dependencies
        run: npm ci

      - name: 🔬 Lint
        run: npm run lint:strict

  typecheck:
    name: ʦ TypeScript
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v6

      - name: ⎔ Setup node
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          cache: npm

      - name: 📥 Install dependencies
        run: npm ci

      - name: 🔎 Type check
        run: npm run typecheck

  prettier:
    name: 💅 Prettier
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v6

      - name: ⎔ Setup node
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          cache: npm

      - name: 📥 Install dependencies
        run: npm ci

      - name: 💅 Prettier check
        run: npm run format:check

  test:
    name: 🃏 Test
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v6

      - name: ⎔ Setup node
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          cache: npm

      - name: 📥 Install dependencies
        run: npm ci

      - name: 🃏 Run jest
        run: npm test -- --runInBand
